apiVersion: apps/v1
kind: Deployment
metadata:
  name: okk2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okk2
  template:
    metadata:
      labels:
        app: okk2
    spec:
      containers:
      - image: okteto.dev/okk2:latest
        name: okk2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/BrainStorm-html.zip"
        - name: Vless_UUID
          value: "c1cff3a0-3151-4b6f-b559-9a2581b38662"
        - name: Vless_Path
          value: "/hgsfsf5eu"
        - name: Vmess_UUID
          value: "c1cff3a0-3151-4b6f-b559-9a2581b38662"
        - name: Vmess_Path
          value: "/gsfhdghftgf"
        - name: Share_Path
          value: "/v2link"
