apiVersion: v1
kind: Service
metadata:
  name: okk2
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okk2"
    port: 8080
  selector:
    app: okk2
